Repository PasinduPrabhashitha/DS-Frontend, pull requests merged in 2023-05, with the labels that each got.

#27 Feature/dev3
  src/components/Store/Store.css
  src/components/Store/StoreHome.jsx
  src/components/Store/img/11.jpg
  src/components/Store/img/111.jpg
  src/components/Store/img/22.jpg
  src/components/Store/img/222.jpg
  src/components/Store/img/33.jpg
  src/components/Store/img/333.jpg
  src/components/Store/img/444.jpg
  src/components/Store/img/sss.jpg
Labels: enhancement

#28 resolve errors
  package-lock.json
  package.json
  src/components/Navigator/Navigator.jsx
  src/components/Store/StoreAdminOrders.jsx
  src/components/Store/StoreAdminPayments.jsx
  src/components/Store/StoreAdminProducts.jsx
  src/components/Store/StoreHome.jsx
  src/components/Store/StoreOrderForm.jsx
  src/components/Users/Register.js
Labels: bug

#29 Feature/dev3
  src/App.js
  src/components/Navigator/Navigator.jsx
  src/components/Store/Store.css
  src/components/Store/StoreAdminOrders.jsx
  src/components/Store/StoreAdminProducts.jsx
  src/components/Store/StoreOrderForm.jsx
  src/components/Store/StoreProductsDetails.jsx
  src/components/Store/StoreShoppingCart.jsx
  src/components/Users/Login.js
Labels: enhancement

#31 Feature/dev3
  package-lock.json
  package.json
  src/components/Navigator/Navigator.jsx
  src/components/Store/Store.css
  src/components/Store/StoreAdminOrders.jsx
  src/components/Store/StoreAdminProducts.jsx
  src/components/Store/StoreHome.jsx
  src/components/Store/StoreProductSingle.js
  src/components/Store/StoreProducts.jsx
  src/components/utils/countriesList.js
  src/components/utils/excel.js
  src/components/utils/index.js
  src/components/utils/state.js
  src/components/utils/validator.js
Labels: enhancement

#34 convert http to https
  .env
  src/components/Navigator/Navigator.jsx
  src/components/Users/Login.js
  src/components/Users/Profile.js
  src/components/Users/Register.js
Labels: bug, documentation

#37 add commision component to the admin routes
  src/App.js
  src/components/Navigator/Navigator.jsx
  src/components/Store/StoreAdminCommision.jsx
Labels: enhancement

#39 current user component added
  src/components/Users/Profile.js
Labels: enhancement

#41 add features to mone page
  src/components/Store/StoreHome.jsx
  src/components/Store/img/1111.jpg
  src/components/Store/img/2222.jpg
  src/components/Store/img/3333.jpg
Labels: enhancement

#50 add table to users order page
  src/components/Users/Profile.js
Labels: enhancement

#52 change css on product details page
  src/components/Store/StoreProductsDetails.jsx
Labels: enhancement

#54 add style to order page
  src/components/Store/StoreShoppingCart.jsx
Labels: enhancement

#55 change the visibility of the cart
  src/components/Navigator/Navigator.jsx
  src/components/Users/Profile.js
Labels: enhancement
